### ISSUE TITLE
6월 20일 회의 사항

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#10]
#### 디렉터리 구조 확정
- 공통 구조 아래 세부 구조 Ex. service -> board, user, etc.

#### 기본 프로젝트 구축
- Maven(pom.xml), context.xml, etc. 정상적으로 동작하는 프로젝트 구축 후 배포 @Junghyo 
- 기본 DB 연동까지 되는 것을 확인해야할 것으로 보임

#### 예정사항
- (알림) DB 설계는 금요일 전까지 윤곽이 보이고 더미데이터를 넣을 수 있을 것으로 보임.

**Comment by AnyhuEkil** [comment]
이제야 읽음
