### ISSUE TITLE
DB 설계 및 구축

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#11]
#### 현재 ERD 6차 업데이트(6/22 16:25)
![image](https://user-images.githubusercontent.com/11993431/27422843-9d131f9e-576a-11e7-8a13-30d313b9ef9b.png)

#### 예정) 설계 작업을 통해 설계 진행
- 관계 정의서
- 용어 사전
- 도메인 정의서
- 속성 정의서
- **CRUD 매트릭스**
- 테이블 정의서

**Comment by llighter** [comment]
Done! 
관계 정의서
용어 사전

**Comment by llighter** [comment]
Done!
도메인 정의서
속성 정의서

**Comment by moneymashi** [comment]
1빠. 굳잡

**Comment by AnyhuEkil** [comment]
굳굳

**Comment by llighter** [comment]
일단 진행상황 공유하려고 올린것입니다.
내일 까지 초안 완성해서 전파할께요 ㅎ @AnyhuEkil

**Comment by AnyhuEkil** [comment]
가상 화폐 DB는 확정.
가상 화폐 활용방안은 미정.
(신용카드로 선결제 후 포인트로 물건 구매 하는 방식)
(포인트 할인.. 등등)
(출석체크 이벤트 - 현재 추가고려사항에 등록되있음.)

테이블은 있으나 실제 사용처는 정해지지 않은것같음.

**Comment by AnyhuEkil** [comment]
옥션 아이템 이미지 컬럼

**Comment by AnyhuEkil** [comment]
그전 회원 아이디 고유화 하자고 했던거에 대한 의견.
날짜데이터 아이디에 적용할예정이라면, rester_date 삭제 해도 무방할듯, 시간정보가 빠지긴 하겠지만..
아니면 ID + RESGI_DATE를 활용하면될것같음.

**Comment by llighter** [comment]
개인 프로필 사진 같은 경우 한장만 저장하면 되서 컬럼이 하나면 되는데
옥션아이템의 경우 여러 사진을 추가하도록 허용하려면 테이블이 따로 필요할 것으로 보임

**Comment by Junghyo** [comment]
확인

**Comment by llighter** [comment]
배송정보(주소, 전화번호, 우편번호, 실제이름), 사진위치, 게시판에 옥선 번호 추가 완료
@AnyhuEkil, @Junghyo @moneymashi @sinew8706

**Comment by llighter** [comment]
auction_item- item_content 컬럼 추가 @moneymashi

**Comment by llighter** [comment]
- [ ] Message_Id 추가

**Comment by moneymashi** [comment]
수고햇어. 내일까지만 더 수고하자 ㅋㅋ

**Comment by AnyhuEkil** [comment]
업데이트 내용 확인.

**Comment by llighter** [comment]
#### DB 설계 완료 :  [Auction DB 설계.pdf](https://drive.google.com/open?id=0B2cqtZKAzlVcQTAtdlRqeVpVUGc)
#### SQL 스키마: [AUCTION.sql](https://drive.google.com/open?id=0B2cqtZKAzlVcV3RnazBNWWsxV0U)

스키마의 경우 바로 전체 실행하면 될것으로 **기대**
확인 후 안되면 문의 바람

**Comment by llighter** [comment]
### 수정사항

#### AUCTION_BOARD
 - BOARD_HIT       NUMBER (4) ->  DEFAULT 0,
 - BOARD_STEP      NUMBER (4) ->  DEFAULT 0,
 - BOARD_INDENT    NUMBER (4) ->  DEFAULT 0,
 - "DATE" -> BOARD_DATE DATE DEFAULT SYSDATE
 - default, date -> BOARD_DATE, sysdate

#### AUCTION_USER, AUCTION_ITEM
 - PICTURE_LOCATION VARCHAR2(100) -> VARCHAR2(500)

#### AUCTION_USER
 - PHONE_NUMBER -> VARCHAR2(11)
 - ZIP_CODE -> VARCHAR2(5)
 - REGISTER_DATE  DATE -> DEFAULT SYSDATE

#### STATE_CODE
STAGE_CODE -> STATE_CODE
STAGE_NAME -> STATE_NAME

#### AUCTION_ITEM
AUTIONEEER_ID -> AUCTIONEER_ID
END_DATRE -> END_DATE

**Comment by llighter** [comment]
### 최종본 완성

#### DB 설계 완료 :  [Auction DB 설계.pdf](https://drive.google.com/open?id=0B2cqtZKAzlVcQTAtdlRqeVpVUGc)
#### SQL 스키마: [AUCTION.sql](https://drive.google.com/open?id=0B2cqtZKAzlVcV3RnazBNWWsxV0U)

@moneymashi @AnyhuEkil @Junghyo @sinew8706

**Comment by llighter** [comment]
최종본 완성으로 이슈를 닫겠음.
