### ISSUE TITLE
6월 21일 회의사항

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#12]
#### 역할분담 세부화
- [proj4-requirements](https://docs.google.com/spreadsheets/d/14emAP49dyADpOgUENaPxrzCYzeTf82_yCZGntEYya0A/edit#gid=1442175965)
  - 9번시트 에서 자신의 업무 및 진행상황 확인 -> **업데이트**

#### 레이아웃 동기화
- 현재 최신 상태의 레이아웃안을 한곳에 동기화 하여야함.
- 수정사항은 반영하여 즉각 동기화 할 것.

#### 프로젝트 구성
- @Junghyo 형이 만든 프로젝트를 베이스로 구성
- 위의 프로젝트를 표준으로 진행(이 프로젝트의 카피본 위에서 작업하는 것을 **원칙**으로 함)

#### 예정사항
- DB: 내일(22일) 까지 기본 명세 완성(현재까지 진행상황 : [Auction DB 설계.pdf](https://drive.google.com/open?id=0B2cqtZKAzlVcQTAtdlRqeVpVUGc))
- DB: 금요일(23일) 까지 로컬에서 구성할 수 있는 스키마 제공
- 기본 프로젝트(22일): 깃헙에 @Junghyo 형이 템플릿을 업로드할 예정
- 카테고리에 대한 세부사항 및 방법 확정
- 레이아웃 동기화 -> @moneymashi 결정 필요
- **22일 정규 회의 일정**

**Comment by AnyhuEkil** [comment]
체크

**Comment by Junghyo** [comment]
확인

**Comment by moneymashi** [comment]
확인.

**Comment by sinew8706** [comment]
확인
