### ISSUE TITLE
메인화면팀 DB테이블 요청사항

### ISSUE THREAD

**Issue by AnyhuEkil** [moneymashi/semiProject#13]
일단 내 생각을 막 적은내용이라, 내 개인적인 생각임.
전체글을 읽어보고 비판적으로 코멘트 달아줬으면 좋겟음.
(잘못된거, 필요 없는거, 다른데서 끌어오면 되는거 등등..)

1. USER_MASSAGE
1.1 (컬럼추가) MASSAGE_ID // (협의됨)
1.2 (컬럼추가) TITLE  // 글제목
1.3. (컬럼추가) SEND_DATE // 발송시간
 (수신시간은 불필요해보임 // RECEIVE(수신여부)로 충분해보임

2. USER_PAYMENT
2.1 (컬럼추가) 카드사(국민, 하나, 삼성, 현대 ) 
2.2 CARD_ID, 테이블 구분용 번호와
    CARD_NO(카드번호) 두가지로 구분했으면 좋겟음.
    (CARD_NO도 충분히 고유값이지만, 정돈된 번호가 있으면함.
개인적으로 모든 테이블마다 ID(INDEX)값이 있어야 된다고 생각..)

3. AUCTION_USER
3.1 USER_PAYMENT 테이블을 -> AUCTION_USER에 넣으면 안되나?
3.2 (컬럼추가)  GRADE
 (추가) AUCTIONEER_INFO LEVEL,STISFACTION 을 GRADE로 통일햇으면 좋겟음.
 결론,
AUCTION_USER 테이블 : USER_GRADE(=BIDDER_GRADE)추가
AUCTIONEER_INFO 테이블 : LEVEL과 SATISFACTION 컬럼을 AUCTIONEER_GRADE로 통합

4. AUCTIONEER_INFO
4.1 잘못씀 (AUCTIONEER_ID이었음.)
4.2 (컬럼추가) 발송정보 필요(유저와 같은 주소정보 발송자이름,주소,우편번호,전화번호)
4.3 (컬럼추가) 돈받을 계좌정보(은행, 계좌번호, 계좌이름 최소 3개는 필요해보임.)

5. AUCTION_BID
5.1 (컬럼추가) BID_ID // 입찰, 낙찰, 종료 화면에 필요함.

6. 낙찰 후 배송테이블(없어도되나?) 관련내용 삭제.

7. AUCTION_ITEM
7.1 (컬럼추가) 현재 입찰자

-----------------------------------

카톡에 올렸던 원문.
DB테이블 개인의견
일단 주저리주저리썻는데, 요약해서 다시한번올리겠음.

1.AUCTION_USER테이블
1.1 배송지 정보 다른 테이블로 분리
배송지등록 가능할지도모르니..
테이블 분리한다면,
배송지 id와 배송지 닉네임 될듯
굳이 분리 필요없으면 말고~
굳이 필요 없다면, 페이먼트도 유저 정보에 합쳐야된다고 생각함.
유저> 개인정보 - 배송지정보-카드정보 동급이라고 생각됨,
각각 분리하던가, 통으로 넣던가??
1,2real_name 아래로...picture는 기존 user 테이블 유지
1.3 판매자 레벨외 구입자 레벨도 필요해보임(패널티, 기타 관리를 위한?)

2.PAYMENT테이블
카드사(국민, 하나, 삼성, 현대 등등.. 필요할듯?)

3.AUCTIONEER_INFO테이블
3.1USER_ID필요해보임-(없이도 테이블 조인?됨?)
레벨과 만족도 굳이 따로 사용해야 할 필요 있음?
(1.3)에 언급했던 사용자 레벨,판매자레벨,만족도
-> 신용도로 바꾸는건 어떤지?
(위 내용이어떻게 됫든간에,, 각 레벨에 따른 정의 테이블 필요
권한 테이블 같이..?
3.2 판매자 주소정보 필요(유저와 같은 주소정보필요해보임)

4.메세지테이블
4.1메세지_ID 추가(협의됨)
4.2메세지 타이틀 없어도되는데 있는게 좋을듯.
4.3.메세지 발송시간은 필요할듯..
 (수신시간은 불필요해보임/수신여부로 충분해보임)

5.비드 테이블
5.1비드 테이블에 비드_ID필요해보임.
입찰, 낙찰, 종료 화면에 필요함.
+ 로그쓸때도 필요해보임.
5.2 현재 입찰자 컬럼 추가요청

5.3 현재 경매현황 컬럼 추가 요청.
(근데 경매 현황을 컬럼 추가를 하면 자동으로 시간에따라 데이터가
변해야되는데가능한가?)
안된다면 그냥 날짜데이터 가지고 조합해서 만들겠음.

6. 낙찰 후 배송테이블(없어도되나?)
주문번호/판매자/아이템/낙찰자/배송상태
(배송관련DB..사이트 너무 자세해서 이정도까진 필요없을듯?)
http://cskstory.tistory.com/entry/%EC%BD%94%EB%93%9C-%ED%85%8C%EC%9D%B4%EB%B8%94-%EC%84%A4%EA%B3%84%ED%95%98%EA%B8%B0

**Comment by AnyhuEkil** [comment]
좀 늦엇음ㅜ

**Comment by llighter** [comment]
#### 1. user_message
- 1.1 완료
- 1.2 완료
- 1.3 RECEIVE_DATE 추가

#### 2. user_payment
- 2.1 완료
- 2.2 완료

#### 3. auction_user
- 3.1 불가 -> 개인이 등록하는 카드가 여러개 일 수 있음
- 3.2 불가 - 레벨은 판매자 등급이고 만족도는 사용자가 평가

#### 4. auctioneer_info
- 4.2 불필요 -> 판매자도 기본적으로 구매자임. 따라서 auction_user의 주소정보를 활용하면 됨
- 4.3 완료

#### 5. auction_bid
- 5.1 완료

#### 6. 보류

#### 7. auction_item
- 7.1 현재 입찰자 추가(세션에서 이름을 유지해야할듯)

**Comment by llighter** [comment]
@AnyhuEkil :)

**Comment by llighter** [comment]
이슈관리를 위해 닫겠습니다. ㅎㅎ
