### ISSUE TITLE
6월 12일 회의사항

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#2]
**추후 고려사항** 
- 물품 하단에 관련 아이템 추천 시스템
- 보증금 시스템 도입 필요 -> 패널티
- 입찰 화면 -> 팝업
- 출석체크 시스템
- 회원 등급(판매자, 구매자) -> 수수료 다르게 적용
- 회원 가입은 간단히 -> 추후 정보등록(배송, 결제, 개인정보)
- 경매 상태 별로 볼 수 있는 필터, 체크박스
- 물품 사진 확대기능
- 가상화폐 도입 -> 화폐를 미리 충전하는 구조
- 고객센터(Q&A) 관련 구현을 어디까지 할 것인지

**Comment by moneymashi** [comment]
1

**Comment by sinew8706** [comment]
확인

**Comment by AnyhuEkil** [comment]
확인햇엇는데?

**Comment by llighter** [comment]
@moneymashi 이슈 닫아도 될 것 같음.
