### ISSUE TITLE
요구사항 분석 준비

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#3]
> ## 확인한 후 덧글 필수!!

### 공지
- 오늘 나눈 이야기 -> #2 를 토대로 내일 요구사항 분석 예정
- 1차 프로젝트와 같이 포스트잇으로 진행할 예정

### 준비사항 
- 작성할 목록(형식은 키워드:내용)
Ex) 로그인: 이메일을 이용하여 접속한다.
- 키워드는 자유( Ex) 로그인, 메인화면, 고객센터, 출석체크 시스템, 등. 내용을 포괄할 수 있는 단어 선택)

### 기한
- 마일스톤에 따라 내일(13일 14시 30분까지) 요구사항 정의분류를 마칠 예정

### 레이아웃
- 위의 정의분류가 완료된후 레이아웃 정규화하는 작업을 수업후(5시30분~)에 진행될 예정.

**Comment by moneymashi** [comment]
1

**Comment by AnyhuEkil** [comment]
#2는 2번 이슈를 뜻함

확인.

**Comment by sinew8706** [comment]
확인

**Comment by Junghyo** [comment]
ㅎㅇ
