### ISSUE TITLE
6월 13일 회의정리

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#4]
> 확인 후 덧글 필수

### 요구사항 분석 1차 완료
- 요구사항 발굴 및 분류 완료
- 요구사항 우선순위 도출 완료
- 세부 항목에 대해서는 구체화 및 팀별로 결정.

### 예정 사항
- 내일(14일) 레이아웃 구체화 예정
- 용어 관리 필요 (ex) 디렉터리, 용어통일.

**Comment by AnyhuEkil** [comment]
고생했당~
