### ISSUE TITLE
###today todo// 회의시간 2시반 ~@@

### ISSUE THREAD

**Issue by moneymashi** [moneymashi/semiProject#5]
### today todo//
- 1. '팀구조 재편성이 필요한가?' 라는 주제. 
 저번주에 구성된 팀은 의견을 너무 급하게 모은게 아닌가 의문..
- 2. 레이아웃 - 특정한 사이트를 기준으로 추가/제거사항을 고려. 
> 메인화면, 회원관리, 검색, 입낙찰.< 
> + Bootstrap은 기정확정. 
> ++ Semantic Tag ui를 쓰는상황이라면 jsp:include 고려사항인가. 아니면 html tag들로 마무리할것인가.
- 3. 디렉터리명 정규화, 프로젝트 폴더명.
 src/auctionweb
 resources(Mapper, mybatis.Spring...), dto, control, service, repository 의 규칙.
 webContent / main
 webContent / bid
- 4. 레이아웃 구성후 주말에 테이블 ERD구체화계획. 
다음주 화요일쯤 데이터 insert가 가능할듯. 
  (데이터주입레 필요한 최소한의 컬럼명과 테이블이름 등 - 종목: 전자기기)
테이블 1차완성전까진 테스트용 테이블을 쓰는것을 타협하기로.

P.S.
++ 추가건의할 사항은 카톡에 말씀하시거나 직접 말씀하시면 되겟습니다!

**Comment by llighter** [comment]
확인했습니다 ㅎ
