### ISSUE TITLE
6월 15일 회의 사항

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#6]
> 확인 후 댓글 필수
#### 레이아웃
1. 메인 - 아마존(상단 바, 슬라이드, 타일)
2. 상단 - 검색, 카테고리 > 드랍다운(option)
3. 입찰화면 - 저번 프로젝트와 상동
4. 입찰 시 - confirm(확인 > 리다이렉트-입찰리스트 조회와 동일, 취소 > 현재 페이지 유지)
5. 개인정보창 - 타일방식 > 새로운 페이지에서 정보 처리
6. 하단 - 사이트 맵, 맨위로 
7. 회원가입, 로그인 - 아마존

### 고려사항
- 페이지 모듈화  : JSP include (혹은 다른 것도 가능)
- 개발 환경 : market - install sts
- 옥션방식: 기본 > 가장 높은 가격, 후보 > Second Highest
- 프로젝트 구조 : 이름 명명 규칙에 따를것 or Spring mvc project
>auctionweb
>>src
>>>resource
>>>>XXXMapper.xml

>>>auction
>>>>controller
>>>>>XXXController.java

>>>>repository
>>>>>XXXDAO.java   (주의: interface file )

>>>>service
>>>>>XXXService.java

>>>>vo
>>>>>XXX.java

>>WebContent
>>>view

**Comment by moneymashi** [comment]
1빠

**Comment by sinew8706** [comment]
확인

**Comment by llighter** [comment]
나두 프로젝투 구조 확인 :)

**Comment by AnyhuEkil** [comment]
첵첵
