### ISSUE TITLE
개발 환경 확정하기

### ISSUE THREAD

**Issue by llighter** [moneymashi/semiProject#7]
개발 환경을 필요한 라이브러리만 가져와서 설정할 것인지?
아니면 STS를 설치해서 사용할 것인지?

@Junghyo 형 한번 알아보죠
조장에게 다음주 월요일까지 시간을 벌었습니다.

**Comment by Junghyo** [comment]
@llighter 
@AnyhuEkil 
@moneymashi 
@sinew8706 
나는 지금 집에서도 sts 환경 구축함.
다른 사람들은 현재 어떻게 진행되고 있는건지?
카톡에 아무런 말도 없길래 다들 잘 되고 있는건가?
문제가 있으면 카톡으로 바로 전달해줘야함.

**Comment by llighter** [comment]
👍
