### ISSUE TITLE
STS 개발환경에 관해서

### ISSUE THREAD

**Issue by Junghyo** [moneymashi/semiProject#8]
@llighter @AnyhuEkil @moneymashi @sinew8706
나는 집에서도 잘됨.
하면서 찾아보고 했는데
STS 빌드 구축시 오류가 생기면 거의 99%는 pom.xml을 통한 라이브러리 생성의 문제임.
pom.xml에 명시한 SPRING이나 JSTL, JDBC 등 기타 필요 라이브러리를 다운받는데
(이건 톰캣이 설치되든 안되든 일단 Spring Project를 만들자마자 자동적으로 다운 받아짐)
제대로 라이브러리를 다운받지 못하는 경우가 있음
(꽤 많음. 나도 2~3번 정도 다시 다운 받음)

해결책
1.  우선 eclipse 또는 STS.exe를 끈다.
2. maven 라이브러리 위치가 보통 C:\Users\컴퓨터계정\.m2\repository 인데
.m2 폴더를 몽땅 삭제
3. 다시 eclipse 또는 STS.exe를 키면 다시 다운 받아진다.

그래서 일단 최소한의 세팅이 
톰캣 설치(본인은 8.5) + Toad(Oracle) + STS프로젝트 + pom.xml을 설정하고
톰캣 돌려서 문제없이 돌아가는 것.
pom.xml은 여기꺼 긁어서 사용(http://doublesprogramming.tistory.com/85)

그 이후에 설정해야 하는게 
log4jdbc 설정, root-context, servlet-context, mybatis-config.xml 설정, jsp 설정 등이
필요한데 다들 알아서 하셨는지?

STS를 사용할꺼라면(난 STS기반에서 진행하길 원함)
일요일+진짜 늦어도 월요일까지는 모든 사람이 STS+MAVEN 빌드구축이 완벽해야 진행하지
안그러면 그냥 바로 포기.
안되는 사람은 카톡으로 바로바로 물어보고

**Comment by llighter** [comment]
넵 저는 오늘 구성할 예정입니다.

👍

**Comment by moneymashi** [comment]
확인. 저도 오늘내일로 설정 마무리할거에요.

**Comment by llighter** [comment]
maven  설정까지 완료!
밑에 부분까지 해야되는데 피곤피곤 열매 먹어서 내일 완료해야할듯합니다.
하지만 sts 활용하는데 문제되는 부분은 없습니다.
💯

**Comment by AnyhuEkil** [comment]
피이고온~열매
